theme: minima
title: Portfolio
first_name: Oscar
last_name: Callejas
email: callejasoc1@gmail.com
description: Welcome to my personal portfolio website where I showcase my projects and skills.
author: Oscar Callejas
github_username: C58R
social: 
  github: www.github.com/C58R
  linkedin: www.linkedin.com/in/oscar-callejas-170761141
  instagram: www.instagram.com/oscar_oc1
  facebook: www.facebook.com/oscar.callejas.3150

domain: oscarcallejas.com
url: https://oscarcallejas.com

lang: en
include:
  - assets/css/style.css

sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all

exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - TODO.md
  - setting.json