remote-theme: jeffreytse/jekyll-theme-yat
plugins: 
  - jekyll-remote-theme

title: Portfolio
first_name: Oscar
last_name: Callejas
email: callejasoc1@gmail.com
description: Welcome to my personal portfolio website where I showcase my projects and skills.

domain: C58R.github.io
url: https://C58R.github.io # the base hostname & protocol for your site
